
version: '2'
services:
  server:
    build:
      context: ./server/
    command: npm start &  sequelize db:migrate
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    ports:
      - "8000:8000"
    # env_file: ./server/.env # TODO - uncomment this to auto-load your .env file!
    environment:
      CONNECTION_STRING_DEV: postgres://user:password@db/db
    links:
        - db
    depends_on:
         - db
  client:
    build:
      context: ./client/
    command: npm run start
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    ports:
      - "80:3000"
  db:
   image: postgres
   ports:
   - "5432:5432"
   environment:
     POSTGRES_PASSWORD: password
     POSTGRES_USER: user
     POSTGRES_DB: db
