
version: '2'
services:
  server:
    build:
      context: ./server/
    command: npm start & npm run db:init
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    ports:
      - "8000:8000"
    environment:
      # env_file: ../server/.env # TODO - uncomment this to auto-load your .env file!
      CONNECTION_STRING_DEV: postgres://user:password@db/db
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      MAIL_SERVICE: ${MAIL_SERVICE}
      PUBLIC_URL: http://nurmaget.com
      NODE_ENV: production;
    links:
        - db
    depends_on:
         - db
  client:
    build:
      context: ./client/
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    ports:
      - "80:80"
  db:
   image: postgres
   ports:
   - "5432:5432"
   environment:
     POSTGRES_PASSWORD: password
     POSTGRES_USER: user
     POSTGRES_DB: db
